{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-challenge-type: "http01"
    {{ if .Values.ingress.wwwRedirect }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{ end }}

spec:
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
    secretName: {{ .Release.Name }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-odoo-server"
          servicePort: {{ .Values.port }}
      - path: /longpolling
        backend:
          serviceName: "{{ .Release.Name }}-odoo-server"
          servicePort: {{ .Values.longpollingPort }}
{{ end }}  
