apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: letsencrypt
    certmanager.k8s.io/acme-challenge-type: "http01"
spec:
  tls:
  - hosts:
    - {{ .Values.domainProd }}
    secretName: {{ .Release.Name }}
  rules:
  - host: {{ .Values.domainProd }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-odoo-server"
          servicePort: {{ .Values.port }}
      - path: /longpolling
        backend:
          serviceName: "{{ .Release.Name }}-odoo-server"
          servicePort: {{ .Values.longpollingPort }}
