apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conf
  labels:
    app: {{ template "odoo-doodba.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.ADMIN_PASSWORD }}
  ADMIN_PASSWORD:  {{ .Values.ADMIN_PASSWORD | b64enc | quote }}
  {{ else }}
  ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
---
{{ if .Values.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smtp-relay
  labels:
    app: {{ template "odoo-doodba.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  relayPassword:  {{ .Values.smtp.relayPass | b64enc | quote }}
---
{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  labels:
    app: {{ template "odoo-doodba.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username:  {{ .Values.postgresql.postgresUser | b64enc | quote }}
  password:  {{ .Values.postgresql.postgresPassword | b64enc | quote }}
