apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-odoo-server
  labels:
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  - name: longpolling
    port: {{ .Values.longpollingPort }}
    targetPort: {{ .Values.longpollingPort }}
    protocol: TCP
  selector:
    app: {{ template "odoo-doodba.fullname" . }}
    type: server
{{ if .Values.smtp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smtp
  labels:
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 25
    name: "25-smtp"
    targetPort: 25
    protocol: TCP
  - port: 465
    name: "465-smtps"
    targetPort: 465
    protocol: TCP
  - port: 587
    name: "587-submission"
    targetPort: 587
    protocol: TCP
  selector:
    app: {{ template "odoo-doodba.fullname" . }}
    type: smtp-relay
{{ end }}
