apiVersion: v1
appVersion: "1.1.6"
description: Odoo chart for Kubernetes using Tecnativa's Docker odoo base (Doodba)
name: odoo-doodba
version: 1.1.6
icon: https://odoocdn.com/openerp_website/static/src/img/assets/png/odoo_logo.png?a=b
sources:
  - https://gitlab.pledra.com/pledra/pledra-helm-charts/tree/master/charts/odoo-doodba
maintainers:
  - name: Paul Catinean
    email: pca@pledra.com
    url: http://pledra.com
keywords:
  - odoo
  - doodba


